2018-08-26 22:49:31,729 INFO [root] [log_conf.py(<module>:25)] - hello
2018-08-26 22:49:31,730 ERROR [root] [log_conf.py(<module>:26)] - error
2018-08-26 22:49:31,731 INFO [root] [utils.py(get_driver:58)] - get_driver
2018-08-26 22:49:40,336 INFO [root] [utils.py(get_driver:58)] - get_driver
2018-08-26 22:49:40,337 INFO [root] [utils.py(get_driver:58)] - get_driver
2018-08-26 22:49:42,308 INFO [root] [test_login.py(test_login:51)] - username=13012345678 password=123456 code=8888 expect=登录成功
2018-08-26 22:49:42,690 INFO [root] [utils.py(get_driver:58)] - get_driver
2018-08-26 22:49:43,371 ERROR [root] [test_login.py(test_login:65)] - False is not true
Traceback (most recent call last):
  File "D:\PycharmProjects\webAutoTestTPshop\script\test_login.py", line 56, in test_login
    self.assertTrue(False)
  File "D:\software\Python36\lib\unittest\case.py", line 682, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
2018-08-26 22:49:43,415 INFO [root] [utils.py(get_driver:58)] - get_driver
2018-08-26 22:49:43,415 INFO [root] [utils.py(get_driver:58)] - get_driver
2018-08-26 22:49:43,415 INFO [root] [utils.py(get_driver:58)] - get_driver
2018-08-26 22:49:43,415 INFO [root] [utils.py(get_driver:58)] - get_driver
2018-08-26 22:49:43,415 INFO [root] [utils.py(get_driver:58)] - get_driver
2018-08-26 22:49:43,415 INFO [root] [utils.py(get_driver:58)] - get_driver
2018-08-26 22:49:43,416 INFO [root] [utils.py(get_driver:58)] - get_driver
2018-08-26 22:49:54,397 INFO [root] [utils.py(get_driver:58)] - get_driver
2018-08-26 22:49:56,681 INFO [root] [utils.py(get_driver:58)] - get_driver
2018-08-26 22:49:58,275 INFO [root] [utils.py(get_driver:58)] - get_driver
2018-08-26 22:50:05,542 INFO [root] [utils.py(get_driver:58)] - get_driver
2018-08-26 22:50:15,251 INFO [root] [log_conf.py(<module>:25)] - hello
2018-08-26 22:50:15,251 ERROR [root] [log_conf.py(<module>:26)] - error
2018-08-26 22:50:15,252 INFO [root] [utils.py(get_driver:58)] - get_driver
2018-08-26 22:50:23,477 INFO [root] [utils.py(get_driver:58)] - get_driver
2018-08-26 22:50:23,477 INFO [root] [utils.py(get_driver:58)] - get_driver
2018-08-26 22:50:25,090 INFO [root] [test_login.py(test_login:51)] - username=13012345678 password=123456 code=8888 expect=登录成功
2018-08-26 22:50:25,434 INFO [root] [utils.py(get_driver:58)] - get_driver
2018-08-26 22:50:25,986 ERROR [root] [test_login.py(test_login:65)] - False is not true
Traceback (most recent call last):
  File "D:\PycharmProjects\webAutoTestTPshop\script\test_login.py", line 56, in test_login
    self.assertTrue(False)
  File "D:\software\Python36\lib\unittest\case.py", line 682, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
2018-08-26 22:50:25,987 INFO [root] [utils.py(get_driver:58)] - get_driver
2018-08-26 22:50:25,988 INFO [root] [utils.py(get_driver:58)] - get_driver
2018-08-26 22:50:25,988 INFO [root] [utils.py(get_driver:58)] - get_driver
2018-08-26 22:50:25,988 INFO [root] [utils.py(get_driver:58)] - get_driver
2018-08-26 22:50:25,988 INFO [root] [utils.py(get_driver:58)] - get_driver
2018-08-26 22:50:25,988 INFO [root] [utils.py(get_driver:58)] - get_driver
2018-08-26 22:50:25,988 INFO [root] [utils.py(get_driver:58)] - get_driver
2018-08-26 22:50:39,636 INFO [root] [utils.py(get_driver:58)] - get_driver
2018-08-26 22:50:41,872 INFO [root] [utils.py(get_driver:58)] - get_driver
2018-08-26 22:50:43,364 INFO [root] [utils.py(get_driver:58)] - get_driver
2018-08-26 22:50:50,049 INFO [root] [utils.py(get_driver:58)] - get_driver
2018-08-26 22:51:48,065 INFO [root] [log_conf.py(<module>:25)] - hello
2018-08-26 22:51:48,065 ERROR [root] [log_conf.py(<module>:26)] - error
2018-08-26 22:51:48,066 INFO [root] [utils.py(get_driver:58)] - get_driver
2018-08-26 22:51:55,859 INFO [root] [utils.py(get_driver:58)] - get_driver
2018-08-26 22:51:55,859 INFO [root] [utils.py(get_driver:58)] - get_driver
2018-08-26 22:51:58,304 INFO [root] [test_login.py(test_login:51)] - username=13012345678 password=123456 code=8888 expect=登录成功
2018-08-26 22:52:02,791 INFO [root] [utils.py(get_driver:58)] - get_driver
2018-08-26 22:52:02,791 INFO [root] [utils.py(get_driver:58)] - get_driver
2018-08-26 22:52:02,792 INFO [root] [utils.py(get_driver:58)] - get_driver
2018-08-26 22:52:02,792 INFO [root] [utils.py(get_driver:58)] - get_driver
2018-08-26 22:52:02,792 INFO [root] [utils.py(get_driver:58)] - get_driver
2018-08-26 22:52:02,792 INFO [root] [utils.py(get_driver:58)] - get_driver
2018-08-26 22:52:02,792 INFO [root] [utils.py(get_driver:58)] - get_driver
2018-08-26 22:52:09,204 INFO [root] [utils.py(get_driver:58)] - get_driver
2018-08-26 22:52:10,474 INFO [root] [utils.py(get_driver:58)] - get_driver
2018-08-26 22:52:11,722 INFO [root] [utils.py(get_driver:58)] - get_driver
2018-08-26 22:52:19,218 INFO [root] [utils.py(get_driver:58)] - get_driver
2018-08-26 22:59:25,053 INFO [root] [log_conf.py(<module>:25)] - hello
2018-08-26 22:59:25,053 ERROR [root] [log_conf.py(<module>:26)] - error
2018-08-26 22:59:25,054 INFO [root] [utils.py(get_driver:58)] - get_driver
2018-08-26 22:59:33,233 INFO [root] [utils.py(get_driver:58)] - get_driver
2018-08-26 22:59:33,233 INFO [root] [utils.py(get_driver:58)] - get_driver
2018-08-26 22:59:34,923 INFO [root] [test_login.py(test_login:51)] - username=13012345678 password=123456 code=8888 expect=登录成功
2018-08-26 22:59:39,673 INFO [root] [utils.py(get_driver:58)] - get_driver
2018-08-26 22:59:39,674 INFO [root] [utils.py(get_driver:58)] - get_driver
2018-08-26 22:59:39,674 INFO [root] [utils.py(get_driver:58)] - get_driver
2018-08-26 22:59:39,674 INFO [root] [utils.py(get_driver:58)] - get_driver
2018-08-26 22:59:39,675 INFO [root] [utils.py(get_driver:58)] - get_driver
2018-08-26 22:59:39,675 INFO [root] [utils.py(get_driver:58)] - get_driver
2018-08-26 22:59:39,675 INFO [root] [utils.py(get_driver:58)] - get_driver
2018-08-26 22:59:52,316 INFO [root] [utils.py(get_driver:58)] - get_driver
2018-08-26 22:59:53,578 INFO [root] [utils.py(get_driver:58)] - get_driver
2018-08-26 22:59:54,010 INFO [root] [utils.py(get_driver:58)] - get_driver
2018-08-26 23:00:00,926 INFO [root] [utils.py(get_driver:58)] - get_driver
